---
title: "Committees"
---

<br/>

## Organizing Committee
- [Romario Ademir Conto López](https://www.itm.edu.co/), Institución Universitaria ITM.
- [Biviana Marcela Suárez Sierra](https://portalqa.omega.eafit.edu.co/profesores/biviana-marcela-suarez-sierra), Universidad EAFIT.
- [Olga Cecilia Usuga Manco](https://www.meetup.com/es/rladies-medellin/), Universidad de Antioquia.
- [Carmen Elena Patiño Rodríguez](https://www.meetup.com/es/rladies-medellin/), Universidad de Antioquia.
- [Freddy Hernández Barajas](https://fhernanb.github.io/), Universidad Nacional de Colombia, sede Medellín.

<br/>

## Cientific Committee
- [Romario Ademir Conto López](https://www.itm.edu.co/), Institución Universitaria ITM (Colombia).
- [Biviana Marcela Suárez Sierra](https://portalqa.omega.eafit.edu.co/profesores/biviana-marcela-suarez-sierra), Universidad EAFIT (Colombia).
- [Olga Cecilia Usuga Manco](https://www.meetup.com/es/rladies-medellin/), Universidad de Antioquia (Colombia).
- [Carmen Elena Patiño Rodríguez](https://www.meetup.com/es/rladies-medellin/), Universidad de Antioquia (Colombia).
- [Benjamín Baumer](https://www.smith.edu/people/ben-baumer), Smith College (USA).
- [Diana Marcela Pérez](https://www.smith.edu/people/ben-baumer), Universidad del País Vasco (España).
- [María Valentina Clavijo Mesa](https://www.meetup.com/es/rladies-medellin/), Politécnico de Milán (Italia).
- [Leticia Ramírez Ramírez](https://www.cimat.mx/), CIMAT (Mexico) 
- [Marco Scavino](https://udelar.edu.uy/portal/), Universidad de la Republica Uruguay (Uruguay).
- [Yandira Cuvero](https://webhistorico.epn.edu.ec/), Escuela Politécnica Nacional de Ecuador (Ecuador).
- [Eniuce Menezes](https://www.uem.br/), Universidade Estadual de Maringá (Brasil).
- [Yasmine Abdelfattah](https://www.upei.ca/cairocampus), University of Prince Edward Island, Egypt Campus (Egipto).
- [Sergio Barajas](https://www.cimat.mx/), CIMAT (México).
- [Jessica María Rojas](https://www.itm.edu.co/), ITM, (Colombia).
- [Carlos Alberto Taimal](https://www.eafit.edu.co/), Universidad EAFIT (Colombia).
- [Isabel Cristina García Arboleda](https://www.javerianacali.edu.co/), Pontificia Universidad Javeriana Cali (Colombia) .
- [Diana Carolina Moreno](https://urosario.edu.co/), Universidad del Rosario (Colombia).
- [Wilmer Pineda Rios](https://usantotomas.edu.co/inicio), Universidad Santo Tomás (Colombia).
- [Andrés Sebastián Rios](https://uis.edu.co/uis-bucaramanga-es/), UIS (Colombia).
- [Alejandra Andrea Tapia Silva](https://www.mat.uc.cl/personas/perfil/alejandra.tapia), Pontificia Universidad Católica de Chile (Chile).
- [Natalia da Silva](https://iesta.fcea.udelar.edu.uy/integrantes/natalia-da-silva/), Universidad de la República de Uruguay (Uruguay).
- [Fidel Ernesto Castro](https://sigaa.ufrn.br/sigaa/public/docente/portal.jsf?siape=1781198), Universidade Federal de Rio Grande do Norte (Brasil).
- [Freddy Hernández Barajas](https://fhernanb.github.io/), Universidad Nacional de Colombia, sede Medellín (Colombia).

<br/>

## Contact
To contact the event organizers, you can write to the email: rdaycolombia@gmail.com

