---
title: "Code of Conduct"
---
<P ALIGN="justify">
Everyone at our event must agree to the following code of conduct. The organizers will enforce this code throughout the event. We expect the cooperation of all participants to help ensure a safe environment for everyone.
<P>

# Do you need help?
If you have any questions about the event, you can write to the email address rdaycolombia@gmail.com.

# Short version
<P ALIGN="justify">
We hope that R Day will be a harassment-free event for everyone, regardless of sex, identity, gender, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), ideology, or technological choices. We do not tolerate harassment of event participants in any form. Sexual language and images are not appropriate anywhere at the event, including talks, workshops, parties, social media, and other online platforms. Event participants who violate these rules may be sanctioned or expelled from the event without a refund at the discretion of the event organizers.
<P>

# Less short version
<P ALIGN="justify">
Harassment includes offensive verbal comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnic origin, religion, ideology, technology choice, sexual images in public spaces, deliberate intimidation, stalking, harassment, following, harassing photography or recording, sustained disruption of conversations or events, inappropriate physical contact, and unwanted sexual attention.
<P>

<P ALIGN="justify">
We expect participants who are asked to stop any harassing behavior to comply immediately. If a participant engages in harassing behavior, the event organizers may take any actions they deem appropriate, including a warning or expulsion from the event without a refund.
<P>

<P ALIGN="justify">
If you are being harassed, see someone else being harassed, or have any comments about it, please contact event staff immediately. Event staff can be identified by their badges.
<P>

<P ALIGN="justify">
Event staff will assist participants in contacting venue security, provide escorts, or help those experiencing harassment feel safe during the conference. We appreciate your attendance at R Day.
<P>

<P ALIGN="justify">
We expect participants to follow these rules both during the event and at related social events.
<P>

Adapted from http://confcodeofconduct.com.
